name: Run Tests on Matrix

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: ['8.3', '8.4'] 

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Make vendor binaries executable
        run: chmod +x vendor/bin/phpunit vendor/bin/pint vendor/bin/rector

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml

      - name: Check code style with Pint
        run: vendor/bin/pint --test

      - name: Run Rector (dry-run)
        run: vendor/bin/rector process --dry-run
